image:
  repository: localhost:32000/sovazlutice
  tag: latest

nginx:
  image: nginx:alpine

host: sovazlutice.hera.danielhnyk.cz

persistence:
  db:
    size: 1Gi
  static:
    size: 512Mi
  media:
    size: 2Gi

resources:
  django:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  nginx:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "100m"
