secrets:
    djangoSecretKey: ENC[AES256_GCM,data:3tfeuJf5a3iPUZowQHp23mkHE1PRIhogF2Bw7lkJEZvDwqcuhvQeCxXY7c7XXGL+TxMT2X8FZ6XPQ5dyI15HtliOcw==,iv:8Wm7yPrnZ5oHIFXjWXXS/fq/fRflIJrtRF7AWrVDOjM=,tag:x8kODPrkUXbg4Y9GZXV6VQ==,type:str]
sops:
    age:
        - recipient: age1nl33y6r6kuv5wz4svfeua48kd7vgz2l9vyqfvy50akmlmkf3a92sfl90s0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM3NwVlVKRnZNWS9hdmNR
            UXRrUkNNVG43bHVncGFuS013TU1JV2Q4RkdNCk1oK2pBMFd0Q0FDc1VZQTQ1Sjha
            eFJ1Umc0eVNGUFlqenQ5aG1GZThvK3cKLS0tIDFhKzFnakQxa293RzFiR3d4QWdN
            aXRaQ1FXL3FBdEhiWHVTT25SQjllN1EKeWNCDQVcTOG55HxE2L0kyiKNwGN6EfVb
            STwjwAyxkfyLS0hexLZnqVypQaC0VE29u4ADPRCoigSq7eqFwVi2Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T11:36:32Z"
    mac: ENC[AES256_GCM,data:2K3ikJDyCSx8evxMMZFHGPuc0RxqSoQqa7wemOiagOTpb5NKBnufc8rgNc4TOYsHwJV2snPO6nev0P9/RduxGS6q+m4yzMRHJPreW5q3TE0DyCdMKpqHiwWxxltx+49civTZ1//IiDoebaVL/WZre0xy5FDFt6/UqJyfG78l+uk=,iv:C5bAjiVtcca3EJrqXBibnMPvHMY9RzmwlRu88qpgfF0=,tag:UfjtINmuaqvzWM0pL8jslw==,type:str]
    encrypted_regex: ^secrets$
    version: 3.11.0
