apiVersion: v1
kind: ConfigMap
metadata:
  name: sovazlutice-nginx
data:
  default.conf: |
    upstream django {
        server 127.0.0.1:8000;
    }

    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /src/static/;
        }

        location /media/ {
            alias /src/media/;
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
